import os
import sqlite3
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import date, datetime, time, timezone
from pathlib import Path
from typing import Any, Iterator, List, Optional

import psycopg
from psycopg.rows import dict_row


VALID_STATUSES = {"novo", "confirmado", "cancelado", "atendido"}
DEFAULT_DATABASE_PATH = Path(__file__).resolve().parents[1] / "data" / "agendamentos.sqlite3"


def get_database_path() -> Path:
    configured_path = os.getenv("APPOINTMENTS_DB_PATH") or os.getenv("DATABASE_PATH")
    if configured_path:
        return Path(configured_path).expanduser()

    configured_dir = os.getenv("APPOINTMENTS_DATA_DIR") or os.getenv("RENDER_DISK_PATH")
    if configured_dir:
        return Path(configured_dir).expanduser() / "agendamentos.sqlite3"

    render_data_dir = Path("/var/data")
    if os.getenv("RENDER") and render_data_dir.exists():
        return render_data_dir / "agendamentos.sqlite3"

    return DEFAULT_DATABASE_PATH


DATABASE_PATH = get_database_path()


def get_database_url() -> Optional[str]:
    database_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
    if not database_url:
        return None
    if not database_url.startswith(("postgres://", "postgresql://")):
        return None
    return database_url


@dataclass(frozen=True)
class AppointmentCreate:
    patient_name: str
    document: str
    service: str
    professional: str
    appointment_date: str
    appointment_time: str


@dataclass(frozen=True)
class AppointmentRecord:
    id: int
    patient_name: str
    document_masked: str
    service: str
    professional: str
    appointment_date: str
    appointment_time: str
    status: str
    created_at: str


def init_db() -> None:
    with connect() as connection:
        if not is_postgres_connection(connection):
            DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)

        execute(
            connection,
            """
            CREATE TABLE IF NOT EXISTS appointments (
                id {id_definition},
                patient_name TEXT NOT NULL,
                document TEXT NOT NULL,
                service TEXT NOT NULL,
                professional TEXT NOT NULL,
                appointment_date {date_type} NOT NULL,
                appointment_time {time_type} NOT NULL,
                status TEXT NOT NULL DEFAULT 'novo'
                    CHECK (status IN ('novo', 'confirmado', 'cancelado', 'atendido')),
                created_at {timestamp_type} NOT NULL,
                deleted_at {timestamp_type}
            )
            """.format(
                id_definition=(
                    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                    if is_postgres_connection(connection)
                    else "INTEGER PRIMARY KEY AUTOINCREMENT"
                ),
                date_type="DATE" if is_postgres_connection(connection) else "TEXT",
                time_type="TIME" if is_postgres_connection(connection) else "TEXT",
                timestamp_type="TIMESTAMPTZ" if is_postgres_connection(connection) else "TEXT",
            ),
        )
        ensure_deleted_at_column(connection)

        if is_postgres_connection(connection):
            execute(
                connection,
                "CREATE INDEX IF NOT EXISTS idx_appointments_date ON appointments (appointment_date)",
            )
            execute(
                connection,
                "CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments (status)",
            )
            execute(
                connection,
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_appointments_active_slot
                ON appointments (appointment_date, appointment_time)
                WHERE status <> 'cancelado' AND deleted_at IS NULL
                """,
            )


def save_appointment(appointment: AppointmentCreate) -> int:
    init_db()
    created_at = datetime.now(timezone.utc).isoformat()
    try:
        with connect() as connection:
            if not is_postgres_connection(connection):
                execute(connection, "BEGIN IMMEDIATE")

            if is_slot_booked_on_connection(
                connection,
                appointment.appointment_date,
                appointment.appointment_time,
            ):
                raise ValueError("Horário indisponível.")

            returning_clause = " RETURNING id" if is_postgres_connection(connection) else ""
            cursor = execute(
                connection,
                f"""
                INSERT INTO appointments (
                    patient_name,
                    document,
                    service,
                    professional,
                    appointment_date,
                    appointment_time,
                    status,
                    created_at
                )
                VALUES (?, ?, ?, ?, ?, ?, 'novo', ?)
                {returning_clause}
                """,
                (
                    appointment.patient_name,
                    mask_document(appointment.document),
                    appointment.service,
                    appointment.professional,
                    appointment.appointment_date,
                    appointment.appointment_time,
                    created_at,
                ),
            )
            if is_postgres_connection(connection):
                row = cursor.fetchone()
                return int(row["id"])
            return int(cursor.lastrowid)
    except psycopg.errors.UniqueViolation as error:
        raise ValueError("Horário indisponível.") from error


def is_appointment_slot_booked(appointment_date: str, appointment_time: str) -> bool:
    init_db()
    with connect() as connection:
        return is_slot_booked_on_connection(connection, appointment_date, appointment_time)


def is_slot_booked_on_connection(
    connection: Any,
    appointment_date: str,
    appointment_time: str,
) -> bool:
    row = execute(
        connection,
        """
        SELECT 1
        FROM appointments
        WHERE appointment_date = ?
          AND appointment_time = ?
          AND status != 'cancelado'
          AND deleted_at IS NULL
        LIMIT 1
        """,
        (appointment_date, appointment_time),
    ).fetchone()

    return row is not None


def list_appointments(
    appointment_date: Optional[str] = None,
    status: Optional[str] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
) -> List[AppointmentRecord]:
    init_db()
    clauses = ["deleted_at IS NULL"]
    params = []

    if appointment_date:
        clauses.append("appointment_date = ?")
        params.append(appointment_date)
    else:
        if start_date:
            clauses.append("appointment_date >= ?")
            params.append(start_date)

        if end_date:
            clauses.append("appointment_date <= ?")
            params.append(end_date)

    if status and status != "todos":
        clauses.append("status = ?")
        params.append(status)

    where_clause = f"WHERE {' AND '.join(clauses)}" if clauses else ""

    with connect() as connection:
        rows = execute(
            connection,
            f"""
            SELECT
                id,
                patient_name,
                document,
                service,
                professional,
                appointment_date,
                appointment_time,
                status,
                created_at
            FROM appointments
            {where_clause}
            ORDER BY appointment_date ASC, appointment_time ASC, id ASC
            """,
            params,
        ).fetchall()

    return [record_from_row(row) for row in rows]


def update_appointment_status(appointment_id: int, status: str) -> Optional[AppointmentRecord]:
    if status not in VALID_STATUSES:
        raise ValueError("Status inválido.")

    init_db()
    try:
        with connect() as connection:
            cursor = execute(
                connection,
                "UPDATE appointments SET status = ? WHERE id = ? AND deleted_at IS NULL",
                (status, appointment_id),
            )

            if cursor.rowcount == 0:
                return None

            row = execute(
                connection,
                """
                SELECT
                    id,
                    patient_name,
                    document,
                    service,
                    professional,
                    appointment_date,
                    appointment_time,
                    status,
                    created_at
                FROM appointments
                WHERE id = ?
                  AND deleted_at IS NULL
                """,
                (appointment_id,),
            ).fetchone()
    except psycopg.errors.UniqueViolation as error:
        raise ValueError("Horário indisponível.") from error

    return record_from_row(row) if row else None


def delete_appointment(appointment_id: int) -> bool:
    init_db()
    deleted_at = datetime.now(timezone.utc).isoformat()
    with connect() as connection:
        cursor = execute(
            connection,
            """
            UPDATE appointments
            SET deleted_at = ?
            WHERE id = ?
              AND deleted_at IS NULL
            """,
            (deleted_at, appointment_id),
        )

    return cursor.rowcount > 0


def ensure_deleted_at_column(connection: Any) -> None:
    if is_postgres_connection(connection):
        execute(
            connection,
            "ALTER TABLE appointments ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ",
        )
        return

    columns = {
        row["name"]
        for row in connection.execute("PRAGMA table_info(appointments)").fetchall()
    }
    if "deleted_at" not in columns:
        connection.execute("ALTER TABLE appointments ADD COLUMN deleted_at TEXT")


def is_postgres_connection(connection: Any) -> bool:
    return isinstance(connection, psycopg.Connection)


def execute(connection: Any, query: str, params: Any = ()) -> Any:
    if is_postgres_connection(connection):
        query = query.replace("?", "%s")
    return connection.execute(query, params)


@contextmanager
def connect() -> Iterator[Any]:
    database_url = get_database_url()
    if database_url:
        connection = psycopg.connect(database_url, row_factory=dict_row)
    else:
        DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
        connection = sqlite3.connect(DATABASE_PATH)
        connection.row_factory = sqlite3.Row
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def record_from_row(row: Any) -> AppointmentRecord:
    return AppointmentRecord(
        id=int(row["id"]),
        patient_name=row["patient_name"],
        document_masked=mask_document(row["document"]),
        service=row["service"],
        professional=row["professional"],
        appointment_date=date_value(row["appointment_date"]),
        appointment_time=time_value(row["appointment_time"]),
        status=row["status"],
        created_at=timestamp_value(row["created_at"]),
    )


def date_value(value: Any) -> str:
    return value.isoformat() if isinstance(value, date) else str(value)


def time_value(value: Any) -> str:
    if isinstance(value, time):
        return value.strftime("%H:%M")
    return str(value)[:5]


def timestamp_value(value: Any) -> str:
    return value.isoformat() if isinstance(value, datetime) else str(value)


def mask_document(document: str) -> str:
    if "*" in document:
        return document
    compact = "".join(character for character in document if character.isalnum())
    if len(compact) <= 4:
        return "*" * len(compact)
    return f"{'*' * (len(compact) - 4)}{compact[-4:]}"
